### PR TITLE
add poster and description from TMDB

### LINKED ISSUE #18: Get movie poster and description from IMDB ID
Get movie poster and description from IMDB ID

### PR DESCRIPTION
**Pull request by ejach**
Closes #18 
image
Requires that a TMDB [API Key](https://www.themoviedb.org/settings/api) be added to `config.php`

### CODE REVIEW

**Review by 9pepsi — APPROVED** [review]

**Comment by ejach** [comment]
Also added the description since it was also fetched from the TMDB API
If no data was retrieved, the normal description will display.
image

**Comment by ejach** [comment]
Added checking to make it so if the IMDB ID doesn't exist, the poster doesn't display.
image

**Comment by ejach** [comment]
This now works for TV shows **and** Movies.
image

**Comment by ejach** [comment]
Fixes #22 
If IMDB ID doesn't exist, don't show the empty IMDB related elements.
Before:
image
After:
image

**Comment by SlideMovies** [comment]
I'll test it, and merge.

**Pull request merged**
